#!/bin/sh
export LD_LIBRARY_PATH=.:./lib
export LANG=en_US.UTF-8

# Start up native streaming server
./sagesrv.sh &
# Start up channel service for dogfood
./chsrv

export SIEGEHOME=/app/sage/skelmir

SIEGEOPT=
if [ -e /tmp/disablejit ]; then
  SIEGEOPT+=" -Xint"
fi
if [ ! -e /rw/sage ]; then
	mkdir /rw/sage
fi

WEBSERVERJARS=ant.jar:core-3.1.1.jar:jetty-6.1.19.jar:jetty-ajp-6.1.19.jar:jetty-rewrite-handler-6.1.19.jar:jetty-sslengine-6.1.19.jar:jetty-starter.jar:jetty-util-6.1.19.jar:jsp-2.1.jar:jsp-2.1-jetty-6.1.19.jar:jsp-api-2.1.jar:sagex-api.jar:servlet-api-2.5-6.1.19.jar

cat Sage.properties.defaults.base Sage.properties.defaults.webserver > /tmp/Sage.properties.defaults

./skelmir/siege -Djava.io.tmpdir=/tmp -Dsage.paths.logs=/tmp/log -Djava.library.path=. -Dsage.paths.cache=/var/media -cp Sage.jar:vecmath.jar:skelmir/Libraries/Apache.jar:jcifs.jar:jce-jdk13-146.jar:apache.jar:jrestubs.jar:$WEBSERVERJARS -Xmx384m $SIEGEOPT sage.Sage 0 0 x "sagetv /rw/sage/Sage.properties" 2>&1 | logger -t s

