#!/bin/sh
cd /app/sage
export LD_LIBRARY_PATH=.:./lib
export LANG=en_US.UTF-8
export SIEGEHOME=/app/sage/skelmir

SIEGEOPT=
[ -e /tmp/disablejit ] && SIEGEOPT="$SIEGEOPT -Xint"

mkdir -p /rw/sage

WEBSERVERJARS=ant.jar:core-3.1.1.jar:jetty-6.1.19.jar:jetty-ajp-6.1.19.jar:jetty-rewrite-handler-6.1.19.jar:jetty-sslengine-6.1.19.jar:jetty-starter.jar:jetty-util-6.1.19.jar:jsp-2.1.jar:jsp-2.1-jetty-6.1.19.jar:jsp-api-2.1.jar:sagex-api.jar:servlet-api-2.5-6.1.19.jar

cat Sage.properties.defaults.base >/tmp/Sage.properties.defaults

exec ./skelmir/siege \
    -Djava.io.tmpdir=/tmp \
    -Dsage.paths.logs=/tmp/log \
    -Djava.library.path=. \
    -Dsage.paths.cache=/rw/sage \
    -cp Sage.jar:vecmath.jar:skelmir/Libraries/Apache.jar:jcifs.jar:jce-jdk13-146.jar:apache.jar:jrestubs.jar:$WEBSERVERJARS \
    -Xmx384m \
    $SIEGEOPT \
    sage.Sage 0 0 "-connect $1" \
    "sagetvclient /rw/sage/SageClient.properties"
