#!/bin/sh

RETVAL=0
PLATFORM=$(cat /etc/platform)

start() {
  # TODO: remove in non-test builds
  if [ -e /rw/startupmods ]; then
    echo Executing startupmods 
    . /rw/startupmods
  fi

  cd /app/sage
  if [ "$PLATFORM" = "GFHD100" ]; then
    (wait-until-created /tmp/ntp.synced; ./runsageclient) &
  else
    (wait-until-created /tmp/ntp.synced; ./runsage) &
  fi

  # TODO: remove in non-test builds
  if [ -e /rw/poststartupmods ]; then
    echo Executing poststartupmods 
    . /rw/poststartupmods
  fi
  echo "Started sageserver $(cat ./version)"
  return $RETVAL
}

stop() {
  pkill siege
  pkill sagesrv
  pkill chsrv
  return $RETVAL
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
