#!/bin/sh

start() {
  # TODO: remove in non-test builds
  if [ -e /rw/startupmods ]; then
    echo Executing startupmods 
    . /rw/startupmods
  fi

  cd /app/sage
  (
    wait-until-created /tmp/ntp.synced
    if is-tv-box; then
      ./runsageclient &
    elif is-storage-box; then
      ./runsage &
    fi
  ) 2>&1 | logger -t s &

  # TODO: remove in non-test builds
  if [ -e /rw/poststartupmods ]; then
    echo Executing poststartupmods 
    . /rw/poststartupmods
  fi
  echo "Started sageserver $(cat /etc/version)"
}

stop() {
  pkill 'runsage|chsrv|sagesrv|siege'
  pkill -f '(babysit.*)?(runsage|chsrv|sagesrv|siege)'
  pkill -9 sagesrv  # doesn't always die happily
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
