#!/bin/sh
PLATFORM=$(cat /etc/platform)
cd /app/client

update_config()
{
  if [ -e /tmp/config ] ; then
    . /tmp/config
    mv /tmp/config /tmp/configold
  fi
  export VIDEO_OUTPUT
  export VIDEO_RESOLUTION
  export AUDIO_OUTPUT
  export VIDEO_SUPPORTED_MODES
  export CACHED_AUTH
  export SERVER_NAME
}

export LD_LIBRARY_PATH=/app/client:/usr/local/lib:$LD_LIBRARY_PATH
export SERIALNUMBER=$(hnvram -qr 1ST_SERIAL_NUMBER)
[ -z "$SERIALNUMBER" ] && SERIALNUMBER=$(hnvram -qr SERIAL_NO)

ulimit -c 49152

SERVER_MAC=
opts=
if [ "$PLATFORM" != "GFHD100" ]; then
  opts="$opts --encodemode"
  mode=miniclient
else
  # TV box starts in powered-off mode
  mode=waitpower
fi

SERVER=127.0.0.1
SERVER_MAC=

while :; do
  update_config  # may change $SERVER or other things
  echo "$0: mode: '$mode'"
  case "$mode" in
    miniclient)
      leds 4  # solid activity light while running miniclient
      [ -n "$SERVER_MAC" ] && [ ! -e /tmp/goalone ] && ether-wake $SERVER_MAC
      ./miniclient $opts "$SERVER"
      mcstate=$?
      SERVER=127.0.0.1
      if [ "$mcstate" != "0" ]; then
        echo "Unexpected exit, miniclient restarting after a delay"
        sleep 10  # prevent high-speed spinning in a loop
      elif [ -e /tmp/runapp ] ; then
        mode=app
      else
        mode=waitpower
      fi
      ;;
    app)
      mv /tmp/runapp /tmp/runappold
      ./run-app
      mode=miniclient
      ;;
    waitpower)
      leds 0  # off while in waitpower mode
      ./waitpower 2>&1 | logger -t waitpower
      mode=miniclient
      ;;
  esac
done
