#!/bin/sh
. /etc/utils.sh

if is-html-tv-ui; then
  echo "configured for chrome"
  exit 0
fi

case "$1" in
  start)
    (
      wait-until-created /tmp/startupvideo.done
      rc_pipe_init
      /app/client/runminiclient 2>&1 | logos miniclient 0 20000000 &
    ) &
    ;;
  stop)
    rm -f /tmp/miracast-listener
    pkillwait -x startupvideo  # if it's running, prevents miniclient from starting up
    pkillwait -x runminiclient
    pkillwait -x miniclient
    pkillwait -x waitpower
    pkillwait -x netflix
    pkillwait -x content_shell
    pkillwait -x vudu
    rc_pipe_deinit
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
