#!/bin/sh
case "$1" in
  start)
    (
      wait-until-created /tmp/startupvideo.done
      /app/client/runminiclient 2>&1 | logos miniclient 100000 &
    ) &
    ;;
  stop)
    pkillwait -x runminiclient
    pkillwait -x miniclient
    pkillwait -x waitpower
    pkillwait -x netflix
    pkillwait -x browsertest
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
