GOOGLE_OREGANO_NATIVE_SITE=repo://vendor/google/oregano-native
GOOGLE_OREGANO_NATIVE_DEPENDENCIES=google_dart_vm google_mcastcapture

ifeq ($(BR2_PACKAGE_GOOGLE_TV_BOX),y)
GOOGLE_OREGANO_NATIVE_DEPENDENCIES += google_cast google_miniclient
endif

define GOOGLE_OREGANO_NATIVE_BUILD_CMDS
	$(MAKE) -C "$(@D)" \
		CROSS_PREFIX="$(TARGET_CROSS)" \
		CFLAGS="$(TARGET_CFLAGS)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) -D__STDC_FORMAT_MACROS" \
		MINICLIENT_PATH="$(GOOGLE_MINICLIENT_DIR)" \
		STAGING_DIR="$(STAGING_DIR)" \
		IS_TV_BOX="$(BR2_PACKAGE_GOOGLE_TV_BOX)" \
		IS_STORAGE_BOX="$(BR2_PACKAGE_GOOGLE_STORAGE_BOX)" \
		build
endef

define GOOGLE_OREGANO_NATIVE_INSTALL_TARGET_CMDS
	$(MAKE) -C "$(@D)" \
		CROSS_PREFIX="$(TARGET_CROSS)" \
		DESTDIR="$(TARGET_DIR)" \
		INSTALL="$(INSTALL)" \
		IS_TV_BOX="$(BR2_PACKAGE_GOOGLE_TV_BOX)" \
		IS_STORAGE_BOX="$(BR2_PACKAGE_GOOGLE_STORAGE_BOX)" \
		install
endef

$(eval $(call GENTARGETS))
