#!/bin/sh
#
# avahi-daemon init script

! is-storage-box && exit 0

case "$1" in
  start)
    nice babysit 60 avahi-daemon 2>&1 | logos avahi &
    ;;
  stop)
    avahi-daemon -c && avahi-daemon -k
    ;;
  reload)
    avahi-daemon -c && avahi-daemon -r
    ;;
  restart)
    stop avahi-daemon
    start avahi-daemon
    ;;
  *)
    echo "Usage: S50avahi-daemon {start|stop|reload|restart}" >&2
    exit 1
    ;;
esac
