#!/bin/sh
. /etc/utils.sh

IP4_DNS="8.8.8.8 8.8.4.4"
IP6_DNS="2001:4860:4860::8888 2001:4860:4860::8844"
NTP="time1.google.com time2.google.com time3.google.com time4.google.com"

ip46tables()
{
  iptables $*
  ip6tables $*
}

start_iptables () {
  ip46tables -t filter -F acs-captive-portal-filter
  iptables -t nat -F acs-captive-portal-nat

  OWN_IP4="$(ip -4 -o addr show dev br0 | pcregrep -o '(\d+\.){3}\d+')"
  OWN_IP6="$(ip -6 -o addr show dev br0 | pcregrep -o '(?<=inet6 )[^/]+')"

  for portal_interface in $(ip -o link | pcregrep -o '\w+_portal'); do
    for dst in $IP4_DNS; do
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p udp -d $dst --dport domain -j ACCEPT
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p tcp -d $dst --dport domain -j ACCEPT

      # for /bin/connection_check
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmp -d $dst --icmp-type echo-request -j ACCEPT
    done

    for dst in $IP6_DNS; do
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p udp -d $dst --dport domain -j ACCEPT
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p tcp -d $dst --dport domain -j ACCEPT

      # for /bin/connection_check
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmpv6 -d $dst --icmpv6-type echo-request -j ACCEPT
    done

    for dst in $NTP; do
      ip46tables -t filter -A acs-captive-portal-filter -i $portal_interface -p udp -d $dst --dport ntp -j ACCEPT
    done

    # allow access to the local DHCP server(s). /bin/wifi will die without it.
    for dst in $OWN_IP4; do
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p udp -d $dst --dport bootps -j ACCEPT
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p tcp -d $dst --dport bootps -j ACCEPT
      iptables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmp -d $dst --icmp-type echo-request -j ACCEPT
    done

    for dst in $OWN_IP6; do
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p udp -d $dst --dport dhcpv6-server -j ACCEPT
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p tcp -d $dst --dport dhcpv6-server -j ACCEPT
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmpv6 -d $dst --icmpv6-type router-solicitation -j ACCEPT
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmpv6 -d $dst --icmpv6-type neighbor-solicitation -j ACCEPT
      ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -p icmpv6 -d $dst --icmpv6-type echo-request -j ACCEPT
    done

    # the ip46tables helper messes with quoted strings
    iptables -t filter -A acs-captive-portal-filter -i $portal_interface -j LOG --log-prefix "iptables: IPv4 reject: "
    ip6tables -t filter -A acs-captive-portal-filter -i $portal_interface -j LOG --log-prefix "iptables: IPv6 reject: "
    ip46tables -t filter -A acs-captive-portal-filter -i $portal_interface -j REJECT

    iptables -t nat -A acs-captive-portal-nat -i $portal_interface -p tcp --dport http -j REDIRECT --to-ports 8888
    iptables -t nat -A acs-captive-portal-nat -i $portal_interface -p tcp --dport https -j REDIRECT --to-ports 8443
    iptables -t nat -A acs-captive-portal-nat -i $portal_interface -p tcp --dport domain -j REDIRECT --to-ports domain
    iptables -t nat -A acs-captive-portal-nat -i $portal_interface -p udp --dport domain -j REDIRECT --to-ports domain
  done
}

stop_iptables () {
  iptables -t nat -F acs-captive-portal-nat
  ip46tables -t filter -F acs-captive-portal-filter
}

case "$1" in
  start)
    babysit 60 setuid nobody sniproxy -f 2>&1 | logos sniproxy &
    start_iptables
    ;;
  stop)
    pkillwait -f "\bsniproxy"
    stop_iptables
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
