#!/bin/sh
cd /app/sage
export LD_LIBRARY_PATH=.:./lib
export LANG=en_US.UTF-8

export SIEGEHOME=/app/sage/skelmir

SIEGEOPT=
if [ -e /tmp/disablejit ]; then
  SIEGEOPT+=" -Xint"
fi
if [ ! -e /rw/sage ]; then
	mkdir /rw/sage
fi
./skelmir/siege -Djava.io.tmpdir=/tmp -Dsage.paths.logs=/tmp/log -Djava.library.path=. -Dsage.paths.cache=/rw/sage -cp Sage.jar:vecmath.jar:skelmir/Libraries/Apache.jar:jcifs.jar:jce-jdk13-146.jar:apache.jar:jrestubs.jar -Xmx384m $SIEGEOPT sage.Sage 0 0 "-connect $1" "sagetvclient /rw/sage/SageClient.properties" 2>&1 | logger -t s

