#!/bin/sh

RETVAL=0
PLATFORM=$(cat /etc/platform)

start() {
  if [ -e /rw/startupmods ]; then
    echo Executing startupmods 
    . /rw/startupmods
  fi

  cd /app/sage
  if [ "$PLATFORM" = "GFHD100" ]; then
    ./runsageclient &
  else
    ./runsage &
  fi

  if [ -e /rw/poststartupmods ]; then
    echo Executing poststartupmods 
    . /rw/poststartupmods
  fi
  return $RETVAL
}

stop() {
  /usr/bin/pkill cvm
  /usr/bin/pkill sagesrv
  /usr/bin/pkill chsrv
  return $RETVAL
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
