#!/bin/sh

case "$1" in
  start)
    mkdir -p /config/dnsmasq
    for d in /config/dnsmasq/*; do
      [ -e "$d" ] || continue
      echo "--- $d: ---"
      cat "$d"
      echo "---"
    done | logos dnsmasq
    babysit 60 dnsmasq \
        --pid-file=/var/run/dnsmasq.pid \
        --conf-file=/etc/dnsmasq.conf \
        --keep-in-foreground \
        --log-facility=- 2>&1 | logos dnsmasq &
    ;;
  stop)
    pkillwait -x dnsmasq
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
