HUMAX_BOOTLOADER_SITE=repo://vendor/humax/bootloader
HUMAX_BOOTLOADER_INSTALL_STAGING=YES
HUMAX_BOOTLOADER_INSTALL_TARGET=YES

HUMAX_BOOTLOADER_STAGING_PATH=usr/lib/humax

define HUMAX_BOOTLOADER_INSTALL_STAGING_CMDS
	mkdir -p $(STAGING_DIR)/$(HUMAX_BOOTLOADER_STAGING_PATH) && \
	$(INSTALL) -m 0755 $(@D)/loader.bin $(STAGING_DIR)/$(HUMAX_BOOTLOADER_STAGING_PATH)
endef

$(eval $(call GENTARGETS))
