#!/bin/sh
. /etc/utils.sh

# Run Chromium/Oregano & Basil, or run Marjoram and Sagesrv
cd "$(dirname "$0")"

export LD_LIBRARY_PATH=/app/client:/usr/local/lib:$LD_LIBRARY_PATH
export SERIALNUMBER=$(hnvram -qr 1ST_SERIAL_NUMBER)
[ -z "$SERIALNUMBER" ] && SERIALNUMBER=$(hnvram -qr SERIAL_NO)

ulimit -c 49152

if is-tv-box; then
  #Basil is the local websocket server allowing Oregano clients to communicate with Miniclient.
  mkdir -p /tmp/libminiclient
  babysit 10 \
      dart -p . isp/fiber/marjoram/src/basil.dart 2>&1 | logos basil 0 20000000 &

  #TODO(codefu): make this url less hard-coded.
  cd /usr/local/bin/webkitGl2

  read epoch < /tmp/client_epoch && PARAMS="${PARAMS}&epoch=$epoch"
  read screenHost < /tmp/screeenHost && PARAMS="${PARAMS}&screenhost=$screenHost"

  #TODO(codefu): Handle authentication.

  #TODO(codefu): Ask spicerack for this either before, or have Oregano query.
  storageHost="192.168.4.6"
  read storageHost < /tmp/storageHost
  PARAMS="${PARAMS}&storageHost=$storageHost"
  PARAMS="${PARAMS}&tvBoxSerial=$SERIALNUMBER"

  echo Oregano params = $PARAMS
  address="https://fiber.google.com/oregano/1/oregano.html"
  read address < /tmp/client_address
  address="$address?$PARAMS"
  echo Oregano addres = $address
  babysit 10 \
      ./start --allow-unsecure-content --remote-debugging-port=9222 --disable-web-security "${address}" 2>&1 | logos oregano 0 20000000 &
else
  start_sagesrv

  # Start up the scheduler / websocket server / spicerack proxy
  babysit 10 \
      setuid video:video dart -p . isp/fiber/marjoram/src/marjoram.dart 2>&1 | logos marjoram 0 20000000 &
fi
