#!/bin/sh
. /etc/utils.sh

if ! is-html-tv-ui; then
  echo "configured for sage"
  exit 0
fi

case "$1" in
  start)
    (
      wait-until-created /tmp/startupvideo.done
      rc_pipe_init
      if is-tv-box; then
        /app/oregano/runoregano 2>&1 | logos oregano 0 20000000 &
      else
        /app/oregano/runmarjoram 2>&1 | logos marjoram 0 20000000 &
      fi
    ) &
    ;;
  stop)
    pkillwait -x startupvideo # if it's running, prevents miniclient from starting up
    pkillwait -f '(babysit.*)(runoregano)'
    pkillwait -x 'runoregano'
    pkillwait -f '(babysit.*)(marjoram\.dart)'
    pkillwait -x 'runmarjoram';
    pkillwait -f '(dart.*)(marjoram\.dart)'
    stop_sagesrv
    stop_adloader
    pkillwait -x waitpower
    pkillwait -x netflix
    pkillwait -x content_shell
    pkillwait -x browser_shell
    pkillwait -x vudu
    rc_pipe_deinit
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
