#!/bin/sh
. /etc/utils.sh

if ! is-html-tv-ui; then
  echo "configured for sage"
  exit 0
fi

case "$1" in
  start)
    (
      wait-until-created /tmp/startupvideo.done
      wait-until-created /tmp/time.synced
      if is-tv-box; then
        /app/oregano/runoregano 2>&1 | logos oregano 0 20000000 &
      fi
    ) &
    ;;
  stop)
    # If startupvideo is running, it prevents miniclient from starting up.
    pkillwait -x startupvideo &
    # Stop the scripts invoked above due to 'start oregano' (which will also
    # stop any babysitters they may have).
    ( pkillwait -x 'runoregano' ;
      # End the Oregano start_chromium binary (which will also end its babysitter).
      pkillwait -x 'start_chromium' ;
      pkillwait -f '(cast|browser|fiber)_shell' ) &
    # End any dangling HTTP request Futures from authTokens.dart attempts.
    pkillwait -f '(dart.*)([a]uthTokens\.dart)' &
    pkillwait -x waitpower &
    pkillwait -x netflix &
    pkillwait -x vudu &
    wait
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
