#
# IGMPPROXY
#

IGMPPROXY_VERSION=0.1
IGMPPROXY_SOURCE=igmpproxy-$(IGMPPROXY_VERSION).tar.gz
IGMPPROXY_SITE:=http://$(BR2_SOURCEFORGE_MIRROR).dl.sourceforge.net/project/igmpproxy/$(IGMPPROXY_VERSION)/$(IGMPPROXY_SOURCE)
IGMPPROXY_DEPENDENCIES =

define IGMPPROXY_INSTALL_DAEMON_INITSCRIPT
	$(INSTALL) -m 0755 package/igmpproxy/S48igmpproxy $(TARGET_DIR)/etc/init.d/
endef

IGMPPROXY_POST_INSTALL_TARGET_HOOKS += IGMPPROXY_INSTALL_DAEMON_INITSCRIPT

$(eval $(call AUTOTARGETS))
