#!/usr/bin/python
# Copyright 2011 Google Inc. All Rights Reserved.
#
"""Replace the sum placeholder in a file (vmlinux) with real data."""

__author__ = 'apenwarr@google.com (Avery Pennarun)'

import sys

marker_pre = '---ROOTFS-SUM-START---\n'
marker_post = '\n---ROOTFS-SUM-END-----\n'

data = sys.stdin.read()
after = data.replace(marker_pre + (' ' * 1024) + marker_post,
                     marker_pre + ('%-1024.1024s' % sys.argv[1]) + marker_post)
assert len(data) == len(after)
assert data != after

sys.stdout.write(after)
