MINDSPEED_DRIVERS_SITE=repo://vendor/mindspeed/drivers
MINDSPEED_DRIVERS_DEPENDENCIES=linux

MINDSPEED_DRIVERS_MAKE = \
	DESTDIR="$(TARGET_DIR)" \
	LINUX_DIR="$(LINUX_DIR)" \
	INSTALL="$(INSTALL)" \
	LINUX_MAKE_FLAGS='$(LINUX_MAKE_FLAGS)' \
	$(MAKE)

define MINDSPEED_DRIVERS_BUILD_CMDS
	$(MINDSPEED_DRIVERS_MAKE) -C $(@D)
endef

define MINDSPEED_DRIVERS_INSTALL_TARGET_CMDS
	$(MINDSPEED_DRIVERS_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
