#!/bin/sh
B=../../out/build

if [ ! -d "$B" ]; then
  echo "$B does not exist; build the software first." >&2
  exit 1
fi

startswith() {
  [ "$1" != "${1#$2}" ]
}

all_packages() {
  local stamp dir pkg
  for stamp in $(cd $B && echo */.stamp_*); do
    dir=$(dirname $stamp)
    [ -L "$B/$dir" ] && continue
    pkg=${dir%%-[0-9]*}
    pkg=${pkg%%-HEAD}
    pkg=${pkg%%-master}
    pkg=${pkg%%-[svRr][0-9]*}
    startswith "$pkg" host- && continue
    echo "$pkg"
  done | sort | uniq
}

all_packages | while read pkg; do
  found=
  for d in licenses/$pkg/*; do
    [ -e "$d" ] && found=1 && break
  done
  [ -n "$found" ] || echo "$pkg"
done
