#! /bin/sh

start_gfcm() {
  # start up client router for gcm
  echo "start gfcm"
  # uncomment the following when ready
  # babysit 60 \
  # /app/gcm/clientrouter \
  # --gcmIdsPath=/rw/gfcm/gcmIds --logtostderr | logos gfcm 0 20000000 &
}

stop_gfcm() {
  # stop client router for gcm
  echo "stop gfcm"
  # uncomment the following when ready
  # pkillwait -f '([b]abysit.*)(clientrouter)'
  # pkillwait -x 'clientrouter'
}

case "$1" in
  start)
    start_gfcm
    ;;
  stop)
    stop_gfcm
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
