#! /bin/sh

# manage miniupnpd and minissdpd, the IGD/NAT-DMP daemons

# this script must be restarted ($0 restart) if the wan address changes
# this script should be run before catawampus (S85catawampus) since catawampus may restart it
# if /tmp/upnpd-enabled is not present, it will be a no-op (catawampus manages that file)

# wan is wan0 on optimus/gfrg200
wan=wan0

setup()
{
  if [ ! -f /tmp/upnpd-enabled ]; then
    echo '/tmp/upnpd-enabled does not exist, refusing to setup.'
    return
  fi
  wanipv4=$(ip addr show $wan | grep 'inet ' | head -n 1)
  wanipv4=${wanipv4%%/*}
  wanipv4=${wanipv4##* }

  # ipv6 and ipv4
  for iptables in ip6tables iptables; do
    $iptables -t filter -F MINIUPNPD
    $iptables -t filter -N MINIUPNPD
    $iptables -t filter -I FORWARD 4 -i $wan ! -o $wan -j MINIUPNPD
  done

  # just ipv4
  for iptables in iptables; do
    $iptables -t nat -F MINIUPNPD
    $iptables -t nat -N MINIUPNPD
    $iptables -t nat -A PREROUTING -d "$wanipv4" -i $wan -j MINIUPNPD
  done
}

cleanup()
{
  for iptables in ip6tables iptables; do
    $iptables -t filter -F MINIUPNPD
    $iptables -t filter -D FORWARD -i $wan ! -o $wan -j MINIUPNPD
    $iptables -t filter -X MINIUPNPD

    $iptables -t nat -F MINIUPNPD
    $iptables -t nat -D PREROUTING -i $wan -j MINIUPNPD
    $iptables -t nat -X MINIUPNPD
  done
}

show()
{
  for iptables in ip6tables iptables; do
    $iptables -v -n -t nat -L PREROUTING
    $iptables -v -n -t nat -L MINIUPNPD
    $iptables -v -n -t filter -L FORWARD
    $iptables -v -n -t filter -L MINIUPNPD
  done
}

start()
{
  if [ ! -f /tmp/upnpd-enabled ]; then
    echo '/tmp/upnpd-enabled does not exist, refusing to start.'
    return
  fi
  if [ ! -s /config/upnp.uuid ]; then
    uuidgen > /config/upnp.uuid
  fi
  uuid=$(cat /config/upnp.uuid)

  sn=$(serial)
  model=$(cat /etc/platform)

  if [ -e /config/nickname]; then
    friendly=$(cat /config/nickname)
  else
    friendly=$(uname -n)
  fi

  lanipv4=$(ip addr show br0 | grep 'inet ' | head -n 1)
  lanipv4=${lanipv4%%/*}
  lanipv4=${lanipv4##* }

  cmd="minissdpd -i br0 -6"
  echo "Running: $cmd"
  eval "$cmd"

  cmd="miniupnpd -i $wan -a '$lanipv4' -u '$uuid' -s '$sn' -m '$model' -z '$friendly' -N"
  echo "Running: $cmd"
  eval "$cmd"
}

stop()
{
  if [ -f /var/run/miniupnpd.pid ]; then
    kill -TERM $(cat /var/run/miniupnpd.pid)
    sleep 1
  fi
  if [ -f /var/run/minissdpd.pid ]; then
    kill -TERM $(cat /var/run/minissdpd.pid)
  fi
}


case "$1" in
  start)
    cleanup
    setup
    start
    ;;
  stop)
    stop
    cleanup
    ;;
  restart)
    stop
    start
    ;;
  show)
    show
    ;;
  setup)
    setup
    ;;
  cleanup)
    cleanup
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|show|setup|cleanup}"
    exit 1
    ;;
esac

exit 0
