QUALCOMM_DRIVERS_SITE=repo://vendor/qualcomm/drivers
QUALCOMM_DRIVERS_DEPENDENCIES=linux

QUALCOMM_DRIVERS_MAKE = \
	TARGET_CROSS="$(TARGET_CROSS)" \
	TARGET_CFLAGS="$(TARGET_CFLAGS)" \
	TARGET_CPPFLAGS="$(TARGET_CPPFLAGS)" \
	TARGET_LDFLAGS="$(TARGET_LDFLAGS)" \
	KERNEL_CROSS="$(TARGET_CROSS)" \
	KERNEL_ARCH="$(KERNEL_ARCH)" \
	TARGET_PATH="$(TARGET_PATH)" \
	LINUX_DIR="$(LINUX_DIR)" \
	STAGING_DIR="$(STAGING_DIR)" \
	TARGET_DIR="$(TARGET_DIR)" \
	INSTALL="$(INSTALL)" \
	$(MAKE)

define QUALCOMM_DRIVERS_BUILD_CMDS
	$(QUALCOMM_DRIVERS_MAKE) -C $(@D)
endef

define QUALCOMM_DRIVERS_INSTALL_TARGET_CMDS
	$(QUALCOMM_DRIVERS_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
