#!/bin/sh

appname=$(awk '{print $1}' /tmp/runappold)

case $appname in
netflix)
  cd /usr/local/bin/netflix
  ./start netflix -I key.bin $(awk '{print $2}' /tmp/runappold)
  ;;
youtube)
  cd /usr/local/bin/browsertest
  ./start browsertest http://www.youtube.com/leanback?version=3
  ;;
*)
  echo Unknown application
  ;;
esac
