#!/bin/sh

RETVAL=0
PLATFORM=$(cat /etc/platform)

start() {
  if [ "$PLATFORM" != "GFHD100" ]; then
    return 0;
  fi
  /app/client/runminiclient &
  return $RETVAL
}

stop() {
  /usr/bin/pkill runminiclient
  /usr/bin/pkill miniclient
  return $RETVAL
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
