HFW_GLAUKUS_LINKMAN_SITE=repo://vendor/hfw/glaukus-linkman
HFW_GLAUKUS_LINKMAN_INSTALL_STAGING=YES
HFW_GLAUKUS_LINKMAN_INSTALL_TARGET=YES

HOST_HFW_GLAUKUS_LINKMAN_DEPENDENCIES=host-hfw_glaukus_hal
HFW_GLAUKUS_LINKMAN_DEPENDENCIES=hfw_glaukus_hal

HFW_GLAUKUS_LINKMAN_HOST_CFLAGS=
HFW_GLAUKUS_LINKMAN_TARGET_CFLAGS=

HOST_HFW_GLAUKUS_LINKMAN_ENV=
HFW_GLAUKUS_LINKMAN_ENV=

HOST_HFW_GLAUKUS_LINKMAN_MFLAGS= \
	CFLAGS=-I$(HOST_DIR)/usr/include \
	XLDFLAGS=-L$(HOST_DIR)/usr/lib \

HFW_GLAUKUS_LINKMAN_MFLAGS= \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	TARGET_CFLAGS=-I$(STAGING_DIR)/usr/include \
	XTARGET_LDFLAGS=-L$(STAGING_DIR)/usr/lib \
	LIB_INSTALL_DIR=$(STAGING_DIR)/usr/lib \
	HEADERS_INSTALL_DIR=$(STAGING_DIR)/usr/include/glaukus \
	TOOLS_INSTALL_DIR=$(TARGET_DIR)/sbin \
	CONFIG_INSTALL_DIR=$(TARGET_DIR)/etc/glaukus \

HOST_HFW_GLAUKUS_LINKMAN_MAKE=$(HOST_HFW_GLAUKUS_LINKMAN_ENV) $(MAKE) $(HOST_HFW_GLAUKUS_LINKMAN_MFLAGS)
HFW_GLAUKUS_LINKMAN_MAKE=$(HFW_GLAUKUS_LINKMAN_ENV) $(MAKE) $(HFW_GLAUKUS_LINKMAN_MFLAGS)

define HOST_HFW_GLAUKUS_LINKMAN_BUILD_CMDS
	$(HOST_HFW_GLAUKUS_LINKMAN_MAKE) -C $(@D) all
endef

define HFW_GLAUKUS_LINKMAN_BUILD_CMDS
	$(HFW_GLAUKUS_LINKMAN_MAKE) -C $(@D) all
endef

define HFW_GLAUKUS_LINKMAN_INSTALL_TARGET_CMDS
	$(HFW_GLAUKUS_LINKMAN_MAKE) -C $(@D) INSTALL_DIR=$(TARGET_DIR)/ install
endef

$(eval $(call GENTARGETS))
$(eval $(call GENTARGETS,host))
