#!/bin/sh
# SUBSYSTEM, ACTION, DEVPATH, and FIRMWARE are all provided by the kernel
# when this script is started.
HOTPLUG_FW_DIR=/lib/firmware
exec >/dev/kmsg 2>&1

if [ "$SUBSYSTEM" = "firmware" -a "$ACTION" = "add" ]; then
  echo "hotplug: sys=$SUBSYSTEM act=$ACTION fw=$FIRMWARE dev=$DEVPATH"
  if [ -f "$HOTPLUG_FW_DIR/$FIRMWARE" ]; then
    echo 1 >/sys/$DEVPATH/loading
    cat "$HOTPLUG_FW_DIR/$FIRMWARE" >/sys/$DEVPATH/data
    echo 0 >/sys/$DEVPATH/loading
  else
    echo -1 >/sys/$DEVPATH/loading
  fi
fi
