#!/bin/sh
case "$1" in
  start)
    if ! is-fiberjack && ! is-spacecast; then
      for ifc in br0 br1; do
        if [ ! -e "/sys/class/net/$ifc" ]; then
          brctl addbr "$ifc"
        fi
      done
    fi
    ;;
  stop)
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
