#!/bin/sh

case "$1" in
  start)
    logmark-once
    if runnable sysvar_cmd; then
      sysvar_cmd -g GOOGLE_SSL_CRT >/dev/random
    fi
    ;;
  stop)
    ;;
  restart|reload)
    $0 stop; $0 start ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
