#!/bin/sh

case "$1" in
  start)
    # Do this early because hnvram needs it.
    update-mtd-links
    logmark-once
    GOOGLE_SSL_CRT=$(hnvram -qr GOOGLE_SSL_CRT)
    [ -z "$GOOGLE_SSL_CRT" ] && echo "GOOGLE_SSL_CRT not set, skipping write to random pool" && exit 1
    echo $GOOGLE_SSL_CRT >/dev/random
    ;;
  stop)
    ;;
  restart|reload)
    $0 stop; $0 start ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
