#!/bin/sh
#
# Start the network....
#

echo "Starting network services"
case "$1" in
  start)
 	echo "Starting network..."
        # :TODO: (by kedong, integrate with outside rcS)
	if [[ "$cmdline" != *nfsroot=* ]]; then
		# set up networking if we are not on an NFS rootfs
		for x in `ls /sys/class/net`; do
			echo "Configuring $x interface"
			/sbin/ifup $x
		done
	else
		# just configure loopback
		/sbin/ifup lo
	fi
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

