#!/bin/sh
case "$1" in
  start)
    mkdir -p /config/staticip
    for f in /config/staticip/*; do
      [ -e $f ] && . $f
    done
    ;;
  stop)
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
