#! /bin/sh
. /etc/utils.sh

case "$1" in
  start|"")
    if interface_exists wan0; then
      babysit 60 netusage -i wan0 2>&1 | logos netusage &
    fi
    ;;
  stop)
    pkill netusage
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: netusage {start|stop|restart}" >&2
    exit 1
    ;;
esac
