#!/bin/sh

# Start the Chimera radio control software

. /etc/utils.sh

start()
{
  echo "starting jsonpoll..."
  babysit 60 jsonpoll 2>&1 | logos jsonpoll &

  echo "starting glaukusd..."
  babysit 60 glaukusd 2>&1 | logos glaukus &
}

stop()
{
  echo "stopping jsonpoll..."
  pkillwait -f jsonpoll

  echo "stopping glaukusd..."
  pkill -INT glaukusd           # shut down cleanly
  pkillwait -f glaukusd         # TERM then KILL
}

# only for chimera
is-ptp || exit 0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
