#!/bin/sh

fssize()
{
  local size
  size=$(df -k $1 | grep / | sed -e 's/  */ /' | cut -f 2 -d ' ')
  size=$(($size + 0))
  echo $size
}

case "$1" in
  start)
    mkdir -p /tmp/cwmp/monitoring/dejittering
    mkdir -p /tmp/cwmp/monitoring/epg
    mkdir -p /tmp/cwmp/monitoring/hdmi
    mkdir -p /tmp/cwmp/monitoring/tcp
    mkdir -p /tmp/cwmp/monitoring/ts
    mkdir -p /tmp/acs
    chmod 777 /tmp/cwmp/monitoring /tmp/cwmp/monitoring/* /tmp/acs
    if is-storage-box; then
      swimage=/var/media/swimage
    elif [ "$(fssize /user)" -ge 1000000 ]; then
      swimage=/user/swimage
    else
      swimage=/tmp/swimage
    fi
    mkdir -p $swimage
    rm -f $swimage/*.gi
    rm -rf $swimage/dnld
    babysit 60 cwmp_monitor | logos cwmp_monitor &
    if is-network-box; then
      DIAGUI="--diagui"
    fi
    if [ -e /tmp/factory_status ]; then
      FACTORY="--factory"
    fi
    # With default CWMPRetryIntervalMultiplier, CWMP
    # maximum exponential backoff is 5120 seconds.
    # Set the alivemonitor to somewhat longer than that.
    babysit 60 \
      alivemonitor /tmp/cwmp/acscontact 300 180 7200 \
      cwmpd $DIAGUI $FACTORY 2>&1 | logos cwmpd 0 20000000 &

    if is-network-box || is-storage-box; then
      poll_hostnames | logos hostnames &
    fi
    ;;
  stop)
    pkillwait -x cwmpd
    pkillwait -f 'alivemonitor.*cwmpd'
    pkillwait -x cwmp_monitor
    pkillwait -x isostream
    pkillwait -x poll_hostnames
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
