#!/bin/sh
case "$1" in
  start)
    (wait-until-created /tmp/ntp.synced; babysit 60 cwmpd) 2>&1 \
        | logos cwmpd &
    ;;
  stop)
    pkillwait -x cwmpd
    ;;

  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
