#!/bin/sh
case "$1" in
  start)
    if runnable cpulog; then
      babysit 60 cpulog --warmup 600 --interval 600 >&1 | logos cpulog &
      babysit 60 cpulog --warmup 600 --interval 14400 >&1 | logos cpulog &
    fi
    ;;
  stop)
    pkillwait -x cpulog
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
