#!/bin/sh
case "$1" in
  start)
    want_psstat=1
    is-spacecast && want_psstat=0
    if [ "$want_psstat" = 1 ]; then
      nice babysit 60 psstat 60 2>&1 | logos ps &
    fi
    nice babysit 60 irqstat 300 2>&1 | logos irq &
    ;;
  stop)
    pkillwait -x psstat
    pkillwait -x irqstat
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
