#!/bin/sh
case "$1" in
  start)
    if is-network-box || is-tv-box || is-fiberjack; then
      babysit 60 psstat 60 2>&1 | logos ps &
    fi
    babysit 60 irqstat 300 2>&1 | logos irq &
    ;;
  stop)
    pkillwait -x psstat
    pkillwait -x irqstat
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
