#!/bin/sh

case "$1" in
  start)
    if [ -e /rw/startupmods ]; then
      echo Executing startupmods
      . /rw/startupmods
    fi

    if [ -e /rw/poststartupmods ]; then
      echo Executing poststartupmods
      . /rw/poststartupmods
    fi
    ;;
  stop)
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
