#!/bin/sh
case "$1" in
  start)
    nice babysit 60 setuid nobody isoping -f1 2>&1 | logos isoping &
    ;;
  stop)
    pkillwait -x isoping
    ;;
  restart|reload)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
