#!/bin/sh

# Nothing good comes of printing stuff to the console. The UART is so
# slow that it noticeably impacts the rest of the system.
# Only panics, KERN_EMERG, and KERN_ALERT will be printed to console.

start()
{
  dmesg -n 1
}

stop()
{
  dmesg -n debug
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
