QUANTENNA_DRIVERS_SITE=repo://vendor/quantenna/drivers
QUANTENNA_DRIVERS_DEPENDENCIES=linux

ifeq ($(BR2_PACKAGE_QUANTENNA_DRIVERS_PCIE_MODULE),y)
QUANTENNA_DRIVERS_FS_DIR=pcie_module
else ifeq ($(BR2_PACKAGE_QUANTENNA_DRIVERS_STANDALONE),y)
QUANTENNA_DRIVERS_FS_DIR=standalone
endif

define QUANTENNA_DRIVERS_INSTALL_TARGET_CMDS
	cp -a $(@D)/fs/common/* $(TARGET_DIR)
	cp -a $(@D)/fs/$(QUANTENNA_DRIVERS_FS_DIR)/* $(TARGET_DIR)
endef

$(eval $(call GENTARGETS))
