QUANTENNA_DRIVERS_SITE=repo://vendor/quantenna/drivers
QUANTENNA_DRIVERS_DEPENDENCIES=linux

ifeq ($(BR2_PACKAGE_QUANTENNA_DRIVERS_PCIE_MODULE),y)
QUANTENNA_DRIVERS_BINARIES_DIR=binaries_pcie_module
else ifeq ($(BR2_PACKAGE_QUANTENNA_DRIVERS_STANDALONE),y)
QUANTENNA_DRIVERS_BINARIES_DIR=binaries_standalone
endif

define QUANTENNA_DRIVERS_INSTALL_TARGET_CMDS
	cp -a $(@D)/$(QUANTENNA_DRIVERS_BINARIES_DIR)/* $(TARGET_DIR)
endef

$(eval $(call GENTARGETS))
