BCM_PLAYREADY_SITE=repo://vendor/broadcom/playready
BCM_PLAYREADY_DEPENDENCIES=bcm_bseav bcm_magnum bcm_nexus bcm_common

PR_MAKE_ENV=\
	PLAYREADY_ROOT=${BCM_PLAYREADY_DIR}/2.5 \
	PLAYREADY_DIR=${BCM_PLAYREADY_DIR}/2.5/source/linux \
	LINUX_BUILD=1 \
	_NTROOT=${BCM_PLAYREADY_DIR}/2.5 \
	PLAYREADY_PROFILE=DrmProfileOEM.mk \
	DRM_BUILD_PROFILE=OEM \
	URSR_TOP=${BCM_PLAYREADY_DIR}/../ \
	PLAYREADY_STANDALONE_BUILD=y


define BCM_PLAYREADY_BUILD_CMDS
	$(BCM_MAKE_ENV) $(PR_MAKE_ENV) $(MAKE) $(BCM_MAKEFLAGS) APPLIBS_TOP=$(@D) -C $(@D)/2.5/source
endef

define BCM_PLAYREADY_INSTALL_TARGET_CMDS
endef

define BCM_PLAYREADY_CONFIGURE_CMDS
	ln -sf $(@D) $(BUILD_DIR)/playready
endef

$(eval $(call GENTARGETS))
