#!/bin/sh
#
# This script mounts all special purpose directories.
#
. /helpers.sh

mount -t devtmpfs none /dev && log "mounted /dev"
mount -t proc none /proc && log "mounted /proc"
mount -t sysfs none /sys && log "mounted /sys"
mkdir /dev/pts /dev/shm
mount -t devpts none /dev/pts && log "mounted /dev/pts"
mount -t tmpfs none /dev/shm && log "mounted /dev/shm"
mount -t debugfs none /sys/kernel/debug && log "mounted /sys/kernel/debug"
