BCM_851XXAPI_SITE=repo://vendor/broadcom/bcm851xx_api
BCM_851XXAPI_INSTALL_STAGING=YES
BCM_851XXAPI_INSTALL_TARGET=NO

HOST_BCM_851XXAPI_DEPENDENCIES=
BCM_851XXAPI_DEPENDENCIES=

BCM_851XXAPI_HOST_CFLAGS=
BCM_851XXAPI_TARGET_CFLAGS=

HOST_BCM_851XXAPI_ENV=
BCM_851XXAPI_ENV=

HOST_BCM_851XXAPI_MFLAGS= \
	CFLAGS=-I$(HOST_DIR)/usr/include \
	XLDFLAGS=-L$(HOST_DIR)/usr/lib \

BCM_851XXAPI_MFLAGS= \
	PCC="$(HOST_DIR)/usr/bin/protoc" \
	CC="$(TARGET_CC)" \
	CXX="$(TARGET_CXX)" \
	LD="$(TARGET_CC)" \
	TARGET_CFLAGS=-I$(STAGING_DIR)/usr/include \
	XTARGET_LDFLAGS=-L$(STAGING_DIR)/usr/lib \
	INSTALL_DIR=$(STAGING_DIR) \

HOST_BCM_851XXAPI_MAKE=$(HOST_BCM_851XXAPI_ENV) $(MAKE) $(HOST_BCM_851XXAPI_MFLAGS)
BCM_851XXAPI_MAKE=$(BCM_851XXAPI_ENV) $(MAKE) $(BCM_851XXAPI_MFLAGS)

BCM_851XXAPI_CONFIGURE_CMDS=

define HOST_BCM_851XXAPI_BUILD_CMDS
	$(HOST_BCM_851XXAPI_MAKE) -C $(@D) all
endef

define BCM_851XXAPI_BUILD_CMDS
	$(BCM_851XXAPI_MAKE) -C $(@D) all
endef

BCM_851XXAPI_ETCDIR = $(TARGET_DIR)/etc/gfch100

define BCM_851XXAPI_INSTALL_STAGING_CMDS
	$(BCM_851XXAPI_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
$(eval $(call GENTARGETS,host))
