GOOGLE_GLOG_SITE = git://github.com/google/glog.git
GOOGLE_GLOG_VERSION = v0.3.4
GOOGLE_GLOG_DIR = $(BUILD_DIR)/google_glog-$(GOOGLE_LOG_VERSION)
GOOGLE_GLOG_INSTALL_STAGING = YES
GOOGLE_GLOG_INSTALL_TARGET = YES

GOOGLE_GLOG_DEPENDENCIES= google_gflags
HOST_GOOGLE_GLOG_DEPENDENCIES= host-google_gflags

GOOGLE_GLOG_CONF_OPT = --enable-static=no

$(eval $(call AUTOTARGETS))
$(eval $(call AUTOTARGETS,host))
