#!/bin/sh
mkdir -p /tmp/cwmp

platform="$(cat /etc/platform)"
case "$platform" in
  GFMS*|GFHD*|GFRG*|GFMN*) board=gfmedia ;;
  GFLT*) board=gfonu ;;
  *) board="$platform" ;;
esac

# A previous run of cwmpd might have left this running.
# run-isostream knows how to kill its children (isostream itself) when
# terminated politely.
pkillwait run-isostream

CWMP="
  /usr/catawampus/cwmpd
      --platform=$board
      --ca-certs=/etc/ssl/certs/ca-certificates.crt
      --restrict-acs-hosts=gfiber-acs-staging.appspot.com,gfiber-acs-prod.appspot.com,gfiber-acs-canary.appspot.com,gfiber-acs-boss.appspot.com,.gfsvc.com,.google.com
"

if [ -s /tmp/ssl/certs/device.pem ] && [ -s /tmp/ssl/private/device.key ]; then
  CWMP="$CWMP --client-cert=/etc/ssl/certs/device.pem"
  CWMP="$CWMP --client-key=/etc/ssl/private/device.key"
fi

exec $CWMP "$@"
