#!/bin/sh
# SpaceCast init script.

# Set the stack size to 1MB (Default to 8M) to support more concurrent streams.
# When CGO is enabled, each blocking syscall (Read, Write) will call
# pthread_create to create a new thread, so stack size for 100 concurrent
# streams would be 800MB and the memory limit would be hit without this change.
ulimit -s 1024

BINARY="/app/spacecast/appliance"

FLAGS="-cache_base_dir=/var/media/data/cache \
       -tmp_dir=/var/media/data/tmp \
       -static_dir=/var/media/static \
       -disable_dir=/var/media/disable \
       -key_dir=/var/media/keys/bandaid/public_keys \
       -api_key_path=/var/media/keys/apiarykey \
       -if_names=lo,br0 \
       -port=8080 \
       -logtostderr=true \
       -stderrthreshold=WARNING"

running() {
  [ -n "$(pgrep -f "$BINARY")" ]
}

case "$1" in
  start)
    if running; then
      echo "SpaceCast is already running!"
    else
      babysit 10 ${BINARY} ${FLAGS} 2>&1 | logos spacecast &
    fi
    ;;
  stop)
    pkill -f "$BINARY"
    ;;
  restart|reload)
    $0 stop;$0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
