#!/bin/sh
#
# Starts dropbear sshd.
#

# Make sure this load is used for test
[ -f /tmp/DEBUG ] || exit 0

start() {
	# Make sure dropbear directory exists.
	#  /etc/dropbear links to /tmp/dropbear, which we can write to.
	if mkdir -p /config/dropbear; then
		ln -sf /config/dropbear /tmp
	else
		mkdir -p /tmp/dropbear
	fi

	# Check for the dropbear keys
	umask 077
	K1=/etc/dropbear/dropbear_rsa_host_key
	K2=/etc/dropbear/dropbear_dss_host_key
	if ! dropbearkey -y -f $K1 >/dev/null 2>&1; then
		[ -e "$K1" ] && echo "BUG: $K1 existed, but invalid!"
		rm -f $K1
		dropbearkey -t rsa -f $K1
	fi
	if ! dropbearkey -y -f $K2 >/dev/null 2>&1; then
		[ -e "$K2" ] && echo "BUG: $K2 existed, but invalid!"
		rm -f $K2
		dropbearkey -t dss -f $K2
	fi

	echo -n "Starting dropbear sshd: "
	start-stop-daemon -S -q -p /var/run/dropbear.pid --exec /usr/sbin/dropbear
	echo "OK"
}
stop() {
	echo -n "Stopping dropbear sshd: "
	start-stop-daemon -K -q -p /var/run/dropbear.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
