#!/bin/sh
case "$1" in
  start)
    (
      wait-until-created /tmp/startupvideo.done
      SERIALNUMBER=$(hnvram -qr 1ST_SERIAL_NUMBER)
      PLATFORM=$(cat /etc/platform)
      /app/client/dialserver -M $PLATFORM -U $SERIALNUMBER 2>&1 | logos dialserver &
    ) &
    ;;
  stop)
    pkillwait -x dialserver
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
