#!/bin/sh
case "$1" in
  start)
    if is-tv-box; then
      dialmonitor | logos dialmonitor &
    fi
    ;;
  stop)
    pkillwait -x dialmonitor
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
