#!/bin/sh
# Monlog Token Pusher init script.

BINARY="/app/spacecast/monlog_pusher"

FLAGS="-logtostderr=true"

running() {
  [ -n "$(pgrep -f "$BINARY")" ]
}

case "$1" in
  start)
    if running; then
      echo "Monlog pusher is already running!"
    else
      babysit 10 ${BINARY} ${FLAGS} 2>&1 | logos monlog_pusher &
    fi
    ;;
  stop)
    pkill -f "$BINARY"
    ;;
  restart|reload)
    $0 stop;$0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
