#!/bin/sh
#
# Spacecast daemon init script.

BINARY="/app/spacecast/daemon"

FLAGS="-logtostderr=true"

# Make sure we have a directory to store Monlog credentials.
mkdir -p /config/monlog

running() {
  [ -n "$(pgrep -f "$BINARY")" ]
}

case "$1" in
  start)
    if running; then
      echo "SpaceCast daemon is already running!"
    else
      babysit 10 ${BINARY} ${FLAGS} 2>&1 | logos scdaemon &
    fi
    ;;
  stop)
    pkill -f "$BINARY"
    ;;
  restart|reload)
    $0 stop;$0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
