HFW_SURPRISE_DIAGNOSTICS_SITE=repo://vendor/hfw/surprise_diagnostics
HFW_SURPRISE_DIAGNOSTICS_INSTALL_STAGING=YES
HFW_SURPRISE_DIAGNOSTICS_INSTALL_TARGET=YES

HOST_HFW_SURPRISE_DIAGNOSTICS_DEPENDENCIES=
HFW_SURPRISE_DIAGNOSTICS_DEPENDENCIES=

HFW_SURPRISE_DIAGNOSTICS_HOST_CFLAGS=
HFW_SURPRISE_DIAGNOSTICS_TARGET_CFLAGS=

HOST_HFW_SURPRISE_DIAGNOSTICS_ENV=
HFW_SURPRISE_DIAGNOSTICS_ENV=

HOST_HFW_SURPRISE_DIAGNOSTICS_MFLAGS= \
	CFLAGS=-I$(HOST_DIR)/usr/include \
	XLDFLAGS=-L$(HOST_DIR)/usr/lib \

HFW_SURPRISE_DIAGNOSTICS_MFLAGS= \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	TARGET_CFLAGS=-I$(STAGING_DIR)/usr/include \
	XTARGET_LDFLAGS=-L$(STAGING_DIR)/usr/lib \
	INSTALL_DIR=$(STAGING_DIR)/usr/include \
	LIB_PREFIX=$(STAGING_DIR)/usr/lib \

HOST_HFW_SURPRISE_DIAGNOSTICS_MAKE=$(HOST_HFW_SURPRISE_DIAGNOSTICS_ENV) $(MAKE) $(HOST_HFW_SURPRISE_DIAGNOSTICS_MFLAGS)
HFW_SURPRISE_DIAGNOSTICS_MAKE=$(HFW_SURPRISE_DIAGNOSTICS_ENV) $(MAKE) $(HFW_SURPRISE_DIAGNOSTICS_MFLAGS)

define HOST_HFW_SURPRISE_DIAGNOSTICS_BUILD_CMDS
	$(HOST_HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) all
endef

define HFW_SURPRISE_DIAGNOSTICS_BUILD_CMDS
	$(HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) all
endef

define HOST_HFW_SURPRISE_DIAGNOSTICS_TEST_CMDS
	true $(HOST_HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) test
endef

define HOST_HFW_SURPRISE_DIAGNOSTICS_INSTALL_CMDS
	true $(HOST_HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) install
endef

define HFW_SURPRISE_DIAGNOSTICS_INSTALL_STAGING_CMDS
	true $(HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) install
endef

define HFW_SURPRISE_DIAGNOSTICS_INSTALL_TARGET_CMDS
	true $(HFW_SURPRISE_DIAGNOSTICS_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
$(eval $(call GENTARGETS,host))
