#!/bin/sh
. /etc/utils.sh
exec >&2

register_experiment NoFastForwarding

if ! runnable cmm || experiment NoFastForwarding; then
  echo "cmm disabled."
  exit 0
fi

echo "Starting cmm."
modprobe -a nfnetlink fci auto_bridge
MAJOR=$(grep vwd /proc/devices | while read a b c; do echo $a; done)
[ -c /dev/vwd0 ] || mknod /dev/vwd0 c $MAJOR 0
echo 1 >/sys/devices/platform/pfe.0/vwd_fast_path_enable

exec cmm -F -f /etc/fastforward.config
