HFW_GLAUKUS_PROTOBUF_SITE=repo://vendor/hfw/glaukus-protobufs
HFW_GLAUKUS_PROTOBUF_INSTALL_STAGING=YES
HFW_GLAUKUS_PROTOBUF_INSTALL_TARGET=NO

HOST_HFW_GLAUKUS_PROTOBUF_DEPENDENCIES=
HFW_GLAUKUS_PROTOBUF_DEPENDENCIES=

HFW_GLAUKUS_PROTOBUF_HOST_CFLAGS=
HFW_GLAUKUS_PROTOBUF_TARGET_CFLAGS=

HOST_HFW_GLAUKUS_PROTOBUF_ENV=
HFW_GLAUKUS_PROTOBUF_ENV=

HOST_HFW_GLAUKUS_PROTOBUF_MFLAGS= \
	CFLAGS=-I$(HOST_DIR)/usr/include \
	XLDFLAGS=-L$(HOST_DIR)/usr/lib \

HFW_GLAUKUS_PROTOBUF_MFLAGS= \
	PCC="$(HOST_DIR)/usr/bin/protoc" \
	CC="$(TARGET_CC)" \
	CXX="$(TARGET_CXX)" \
	LD="$(TARGET_CC)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	TARGET_CFLAGS=-I$(STAGING_DIR)/usr/include \
	XTARGET_LDFLAGS=-L$(STAGING_DIR)/usr/lib \
	LIB_INSTALL_DIR=$(STAGING_DIR)/usr/lib \
	HEADERS_INSTALL_DIR=$(STAGING_DIR)/usr/include/glaukus/proto \

HOST_HFW_GLAUKUS_PROTOBUF_MAKE=$(HOST_HFW_GLAUKUS_PROTOBUF_ENV) $(MAKE) $(HOST_HFW_GLAUKUS_PROTOBUF_MFLAGS)
HFW_GLAUKUS_PROTOBUF_MAKE=$(HFW_GLAUKUS_PROTOBUF_ENV) $(MAKE) $(HFW_GLAUKUS_PROTOBUF_MFLAGS)

HFW_GLAUKUS_PROTOBUF_CONFIGURE_CMDS=

define HOST_HFW_GLAUKUS_PROTOBUF_BUILD_CMDS
	$(HOST_HFW_GLAUKUS_PROTOBUF_MAKE) -C $(@D) all
endef

define HFW_GLAUKUS_PROTOBUF_BUILD_CMDS
	$(HFW_GLAUKUS_PROTOBUF_MAKE) -C $(@D) all
endef

HFW_GLAUKUS_PROTOBUF_ETCDIR = $(TARGET_DIR)/etc/gfch100

define HFW_GLAUKUS_PROTOBUF_INSTALL_STAGING_CMDS
	$(HFW_GLAUKUS_PROTOBUF_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
$(eval $(call GENTARGETS,host))
