#!/bin/sh
. /etc/utils.sh

register_experiment WifiPrimarySpreading
register_experiment WifiUseActiveTime
register_experiment WifiChannelsLimited2G
register_experiment WifiLowIsHigh
register_experiment WifiUseDFS

case "$1" in
  start)
    # TODO(awdavies): For now we want to avoid running more daemons on MN than
    # we need to.  This is until we've fixed our RAM woes.
    if is-windcharger; then
      exit 1
    fi

    if is-network-box; then
      babysit 60 alivemonitor /tmp/waveguide/alive 10 10 60 \
          waveguide --high-power --scan-interval=300 2>&1 | logos waveguide &
    elif has_wifi && runnable iw; then
      supernice babysit 60 alivemonitor /tmp/waveguide/alive 10 10 600 \
          waveguide --no-high-power --scan-interval=300 2>&1 | logos waveguide &
    fi
    ;;
  stop)
    pkillwait -f waveguide
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
