PF_RING_SITE=repo://vendor/opensource/pf_ring
PF_RING_DEPENDENCIES=linux

PF_RING_MAKE = \
  DESTDIR="$(TARGET_DIR)" \
	LINUX_DIR="$(LINUX_DIR)" \
	LINUX_MAKE_FLAGS='$(LINUX_MAKE_FLAGS)' \
	TARGET_CROSS="$(TARGET_CROSS)" \
	TARGET_CFLAGS="$(TARGET_CFLAGS)" \
	TARGET_CPPFLAGS="$(TARGET_CPPFLAGS)" \
	TARGET_DIR="$(TARGET_DIR)" \
	TARGET_LDFLAGS="$(TARGET_LDFLAGS)" \
	KERNEL_CROSS="$(TARGET_CROSS)" \
	KERNEL_ARCH="$(KERNEL_ARCH)" \
	TARGET_PATH="$(TARGET_PATH)" \
	STAGING_DIR="$(STAGING_DIR)" \
	INSTALL="$(INSTALL)" \
	$(MAKE)

define PF_RING_BUILD_CMDS
	$(PF_RING_MAKE) -C $(@D)
endef

define PF_RING_INSTALL_TARGET_CMDS
	$(PF_RING_MAKE) -C $(@D) install
endef

$(eval $(call GENTARGETS))
