#!/bin/sh

case "$1" in
  start)
    babysit 60 setuid nobody minissdpd -i br0 -6 -d 2>&1 | logos ssdpd &
    ;;
  stop)
    pkillwait minissdpd
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
