#!/bin/sh

make_new_ntp_conf()
{
  cat /etc/ntpd.conf.default /tmp/ntpd4.conf /tmp/ntpd6.conf \
    2>/dev/null >/tmp/ntpd.conf.new

  if cmp /tmp/ntpd.conf.new /tmp/ntpd.conf >/dev/null; then
    rm -f /tmp/ntpd.conf.new
    echo No changes in NTP Configuration | logger -t dhcpexithook
    return
  fi
  mv /tmp/ntpd.conf.new /tmp/ntpd.conf

  cat /tmp/ntpd.conf | while read line ; do
    echo "ntpd.conf: $line" 2>&1 | logger -t dhcpexithook
  done

  /etc/init.d/S75ntpd restart
}


write_ntp_conf_new()
{
  fname=$1
  rm -f $fname

  if [ -z "$new_ntp_servers" ]; then
    echo no new ntp servers 2>&1 | logger -t dhcpexithook
    return
  fi

  for server in $new_ntp_servers; do
    echo "server $server" >>$fname
  done
}


# NTP server handling
case $reason in
  BOUND|RENEW|REBIND|REBOOT)
    write_ntp_conf_new /tmp/ntpd4.conf
    make_new_ntp_conf
    ;;

  BOUND6|RENEW6|REBIND6|REBOOT6)
    write_ntp_conf_new /tmp/ntpd6.conf
    make_new_ntp_conf
    ;;

  EXPIRE|FAIL|RELEASE|STOP)
    echo Removing DHCP4 ntp servers on $reason 2>&1 | logger -t dhcpexithook
    rm -f /tmp/ntpd4.conf
    make_new_ntp_conf
    ;;

  EXPIRE6|FAIL6|RELEASE6|STOP6)
    echo Removing DHCP6 ntp servers on $reason 2>&1 | logger -t dhcpexithook
    rm -f /tmp/ntpd6.conf
    make_new_ntp_conf
    ;;

esac
