#!/bin/sh
case "$1" in
  start)
    syslogd -m 0
    klogd &
    babysit 60 logmark &
    ;;
  stop)
    pkillwait -x syslogd
    pkillwait -x klogd
    pkillwait -x logmark
    ;;
  restart|reload)
    $0 stop; $0 start ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
