#!/bin/sh

case "$1" in
  start)
  	# make sure gpio-mailbox has had at least one loop
  	wait-until-created /tmp/gpio/ready
  	
  	if reset-button-held 4000; then
  	      zap --i-really-mean-it
 	      # zap reboots the machine so we should never reach here
 	fi
	;;
  stop)
  	pkill switch-on-reset
	;;
  restart)
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
