#!/bin/sh
[ -x /usr/sv/startupvideo ] || exit 0

case "$1" in
  start)
    if is-tv-box; then
      wait-until-created /var/run/gpio-mailbox
      echo "Starting startupvideo."
      mknod /tmp/svpipe p
      (
        /usr/sv/startupvideo /tmp/svpipe \
          /usr/sv/Google_Loading_Loop_HiRes2.ts 2 0 1001 1002 \
          /usr/sv/connecting.ts 1 0 256 0
        echo : >/tmp/startupvideo.done
      ) 2>&1 | logger -t startupvideo &
      (
        wait-until-created /tmp/ntp.synced
        echo y >/tmp/svpipe
      ) 2>&1 | logger -t startupvideo &
    else
      (
        wait-until-created /tmp/ntp.synced
        echo : >/tmp/startupvideo.done
      ) 2>&1 | logger -t startupvideo &
    fi
    ;;
  stop)
    pkillwait -x startupvideo
    rm -f /tmp/svpipe
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac
