#!/bin/sh

case "$1" in
  start)
    babysit 10 softdog 2>&1 | logger -t softdog &
    ;;
  stop)
    pkillwait -x softdog
    ;;

  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
