#!/bin/sh

if [ ! -e /dev/btusb0 ]; then
	exit 0
fi

BT_MAC_ADDR=`hnvram -rq MAC_ADDR_BT`

case "$1" in
  start)
	echo -n "Starting app_gtv service: "
	cd /user/bsa
	babysit 30 app_gtv -a "${BT_MAC_ADDR}" -k 2>&1 | logger -t app_gtv &
	echo "done"
	;;
  stop)
	echo -n "Shutting down app_gtv service: "
	pkill -x app_gtv
	echo "done"
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
