#!/bin/sh

if [ ! -e /dev/btusb0 ]; then
	exit 0
fi

BT_MAC_ADDR=`hnvram -rq MAC_ADDR_BT`
BT_NAME=`hnvram -rq PLATFORM_NAME`

case "$1" in
  start)
	cd /user/bsa
        babysit 30 app_gtv -a "${BT_MAC_ADDR}" -n "${BT_NAME}" -k \
            2>&1 | logger -t app_gtv &
	;;
  stop)
	pkillwait -x app_gtv
	;;

  restart)
	$0 stop; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
