#!/bin/sh

case "$1" in
  start)
	wifi="eth2"
	wifisys=/sys/class/net/${wifi}/address

	if [ -f $wifisys ] ; then
	  echo -n "Initializing Wifi service: "
	  wifimac=$(cat $wifisys)
	  wl ap 1
	  wl radio off
	  wl bssid "$wifimac"
	  echo "done"
	fi
	;;
  stop)
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
