#!/bin/sh

case "$1" in
  start)
    # Mount SATA device
    if [ -e /dev/sda ]; then
      echo "Mounting SATA device"
      if [ -e /dev/sda1 ]; then
        mount -o noatime,barrier=0,data=writeback,noexec,nosuid,nodev -t ext4 /dev/sda1 /var/media
        [ -e /dev/sda2 ] && mount -o noatime,noexec,nosuid,nodev -t ext4 /dev/sda2 /var/backup
      elif [ -h /dev/sda ]; then
        mount -o noatime,barrier=0,data=writeback -t ext4 /dev/sda /var/media
      fi
    fi
    ;;
  stop)
    # Unmount SATA device
    echo "Unmounting SATA device"
    umount /var/media 2>&1 >/dev/null
    umount /var/backup 2>&1 >/dev/null
    ;;
  restart|reload)
    "$0" stop
    sleep 3
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
