#!/bin/sh

start() {
  mkdir -p /user/diag
  babysit 60 diagd  2>&1 | logger -t diagd &
}

stop() {
  pkill -x diagd
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit
