#!/bin/sh
case "$1" in
  start)
    mkdir -p /tmp/cwmp/monitoring/dejittering
    mkdir -p /tmp/cwmp/monitoring/epg
    mkdir -p /tmp/cwmp/monitoring/hdmi
    mkdir -p /tmp/cwmp/monitoring/tcp
    mkdir -p /tmp/cwmp/monitoring/ts
    chmod 777 /tmp/cwmp/monitoring /tmp/cwmp/monitoring/*
    babysit 60 cwmpd 2>&1 | logos cwmpd &
    ;;
  stop)
    pkillwait -x cwmpd
    ;;
  restart)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
