#!/bin/sh

case "$1" in
  start)
	if [ -d /var/media/videos ] && \
	    [ ! -f /var/media/videos/Samples/GoogleFiber.mov ] && \
	    [ ! -f /var/media/.mfgmedia ] ; then
		mkdir -p /var/media/videos/Samples
		cp /usr/lib/media/GoogleFiber.mov /var/media/videos/Samples/GoogleFiber.mov
		cp /usr/lib/media/GoogleFiber.mov /var/media/videos/Samples/GoogleFiber1.mov
		echo '' > /var/media/.mfgmedia
	fi
	;;
  stop)
	;;
  restart)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
