#!/bin/sh

case "$1" in
  start)
	if [ -f /var/media/.mfgmedia ] ; then
		# remove detritus from previous mfg burnin support
		rm -f /var/media/videos/GoogleFiber.mov
		rm -f /var/media/videos/Samples/GoogleFiber.mov
		rm -f /var/media/videos/Samples/GoogleFiber1.mov
		if [ -d /var/media/videos/Samples ]; then
			rmdir /var/media/videos/Samples
		fi
		rm -f /var/media/.mfgmedia
	fi
	if [ ! -f /var/media/.mfgmedia2 ] ; then
		cp /usr/lib/media/GoogleFiber.mov /var/media/ManufacturingBurnin.mov

		mkdir -p /var/media/pictures/Landscapes
		cd /usr/lib/media/landscapes/
		for file in *
		do
		  cp "$file" /var/media/pictures/Landscapes
		  chmod 555 /var/media/pictures/Landscapes/"$file"
		done

		echo done >/var/media/.mfgmedia2
	fi
	;;
  stop)
	;;
  restart)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
