#!/bin/sh

case "$1" in
  start)
	# remove detritus from previous mfg burnin support
	if [ -f /var/media/.mfgmedia ] ; then
		rm -f /var/media/videos/GoogleFiber.mov
		rm -f /var/media/videos/Samples/GoogleFiber.mov
		rm -f /var/media/videos/Samples/GoogleFiber1.mov
		if [ -d /var/media/videos/Samples ]; then
			rmdir /var/media/videos/Samples
		fi
		rm -f /var/media/.mfgmedia
	fi
	if [ -d /var/media/videos ] && [ ! -f /var/media/ManufacturingBurnin.mov ] ; then
		cp /usr/lib/media/GoogleFiber.mov /var/media/ManufacturingBurnin.mov
	fi
	;;
  stop)
	;;
  restart)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
