#!/bin/sh

# Check that smb.conf exists.
[ -f /etc/samba/smb.conf ] || exit 0

# Make directories.
mkdir -p /var/cache/samba
mkdir -p /var/log/samba
mkdir -p /var/lock/subsys
mkdir -p /tmp/samba/sockets

start() {
	if [ -d /var/media/videos ]; then
		echo -n "Starting SMB service"
		smbd -S -F 2>&1 </dev/null | logger -t smbd &

		echo -n "Starting NMB service"
		nmbd -S -F 2>&1 </dev/null | logger -t nmbd &
	fi
	return 0
}

stop() {
	echo -n "Shutting down SMB service"
	kill -9 `pidof smbd`
	rm -f /var/run/smbd.pid

	echo -n "Shutting down NMB service"
	kill -9 `pidof nmbd`
	rm -f /var/run/nmbd.pid

	return 0
}

restart() {
	stop
	start
}

reload() {
	echo -n "Reloading smb.conf file"
	kill -HUP `pidof smbd`
	return 0
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
