#!/bin/sh

[ -e /etc/samba/smb.conf ] || exit 0

mkdir -p /var/cache/samba /var/lock/subsys /tmp/samba/sockets

case "$1" in
  start)
    if [ -d /var/media/videos ]; then
      babysit 60 smbd -F -D -S 2>&1 | logger -t smbd &
      babysit 60 nmbd -F -D -S 2>&1 | logger -t nmbd &
    fi
    ;;
  stop)
    # we have to kill the babysitter too, because smbd eats the SIGTERM
    # exit code and returns 1 instead, so babysit thinks it needs to
    # restart.
    pkillwait -f 'babysit 60 smbd'
    pkillwait -f 'babysit 60 nmbd'
    pkillwait -x smbd
    pkillwait -x nmbd
    ;;
  restart)
    $0 stop; $0 start
    ;;
  reload)
    pids=$(pgrep -x smbd)
    [ -n "$pids" ] && kill -1 $pids
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
