#!/bin/sh
case "$1" in
  start)
    babysit 60 cpulog --warmup 600 --interval 600 >&1 | logger -t cpulog &
    babysit 60 cpulog --warmup 600 --interval 14400 >&1 | logger -t cpulog &
    ;;
  stop)
    pkillwait -x cpulog
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
