#!/bin/sh
case "$1" in
  start)
    babysit 60 psstat 60 2>&1 | logger -t ps &
    ;;
  stop)
    pkillwait -x psstat
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
