#!/bin/sh
case "$1" in
  start)
    babysit 60 ubifsmonitor 2>&1 | logos ubifsmonitor &
    ;;
  stop)
    pkillwait -x ubifsmonitor
    ;;
  restart|reload)
    $0 stop; $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
