#!/bin/sh
case "$1" in
  start)
    babysit 60 vmstat 5 2>&1 | logger -t vmstat &
    ;;
  stop)
    pkillwait -x vmstat
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
