#! /bin/sh

. /etc/utils.sh

# called from ifplugd

iface="$1"
action="$2"

case "$action" in
  up)
    if [ "$iface" = pon0 ]; then
      # Fiber Jack
      ethtool -r eth0
      ifup man
    fi
    if [ "$iface" = wan0 ]; then
      # Network Box
      run-dhclient "$iface"
      if interface_exists wan0.2; then
        run-dhclient wan0.2
      fi
    fi
    ;;
  down)
    if [ "$iface" = pon0 ]; then
      ethtool -r eth0
    fi
    ;;
  *)
    echo "$0: unknown action '$action'"
    exit 1
esac
exit 0
