#!/bin/sh

IFNAME=
APIMODE=

if is-fiberjack; then
  IFNAME=pon0
elif is-spacecast; then
  IFNAME=lan0
elif is-network-box; then
  IFNAME=wan0
  APIMODE="--api-mode=iff"
fi

start()
{
  if [ -n "$IFNAME" ] ; then
    babysit 60 ifplugd $APIMODE -i $IFNAME -n -s -f -I -p -q -d0 2>&1 | logos ifplugd &
  fi
}

stop()
{
  if [ -n "$IFNAME" ] ; then
    ifplugd -k -W -i $IFNAME
  fi
  pkill ifplugd.action
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  sleep)
    sleep 60
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
